### ISSUE TITLE
Travis CI Integration

### ISSUE THREAD

**Issue by robertoaloi** [happi/theBeamBook#10]
It would be great to get some basic CI pipeline in place, so that only Pull Requests which would not break compilation could be merged. The pipeline could also be used to ensure that the generated PDF and HTML are stored as artifacts, so that readers would not need to build their own.

**Comment by happi** [comment]
Yes. It is on the todo....
I'll add you as an contributor and you are free to go wild.

**Comment by robertoaloi** [comment]
Great. I will try to get a pipeline in place.

**Comment by robertoaloi** [comment]
Done. We should enable Github Pages for this repo, though.
