### ISSUE TITLE
Misprint or not?

### ISSUE THREAD

**Issue by anton-ryabkov** [happi/theBeamBook#100]
In the chapter 1.3.2 you example some OTP behaviours, one of them _gen_ftp_:

> The fifth layer, OTP, supplies the Erlang standard libraries. OTP originally stood for "Open Telecom Platform" and was a number of Erlang libraries supplying building blocks (such as supervisor, gen_server and gen_ftp) 

 May be you means _gen_tcp_?

**Comment by happi** [comment]
Yes, thanks.
