### ISSUE TITLE
Typo on BEAM instructions

### ISSUE THREAD

**Issue by sunboshan** [happi/theBeamBook#101]
> call Arity Label
> Does a call to the function of arity Arity in the same module at label Label. First count down the reductions and if needed do a context switch. Current code address **before** the call is saved into CP.

The `before the call` should be `after the call`.

Source code [ref](https://github.com/erlang/otp/blob/OTP-20.1/lib/compiler/src/genop.tab#L43-L46).

**Comment by sunboshan** [comment]
Few more typo:

```
call_last Arity Label
Do a tail recursive call the function of arity Arity in the same module at label Label. First count down the reductions and if needed do a context switch. The CP is not updated with the return address.

call_only Arity Label Deallocate
Deallocate Deallocate words of stack, then do a tail recursive call to the function of arity Arity in the same module at label Label First count down the reductions and if needed do a context switch. The CP is not updated with the return address.
```

Should switch the function name:
```
call_only Arity Label
call_last Arity Label Deallocate
```

Souce code [ref](https://github.com/erlang/otp/blob/OTP-20.1/lib/compiler/src/genop.tab#L48-L57).

**Comment by kvakvs** [comment]
Modified according to the notes. Merged. Thanks.
