### ISSUE TITLE
Possible typo in section "7.2 BEAM code listings"

### ISSUE THREAD

**Issue by sadesyllas** [happi/theBeamBook#128]
First of all, thanks a lot for your great work! :slightly_smiling_face: :+1: 

In the last paragraph of section `7.2 BEAM code listings`, right above section `7.3 Calls` (pdf page 96) it reads:

> Then the instruction {move,{atom,beamexample1},{x,0}} moves the module name atom to the first argument register x1

Doesn't `{x,0}` mean that it moves it to `x0`?

**Comment by happi** [comment]
Yes of course. Good catch. Thanks.

**Comment by happi** [comment]
Fixed in https://github.com/happi/theBeamBook/commit/cf7a4374e7ddbb4a222a6d1e31ab3c935d4d8e52
No new pdf released yet.
