### ISSUE TITLE
Build the PDF artefact and tag it as release version

### ISSUE THREAD

**Issue by posilva** [happi/theBeamBook#13]
Hi,

it would be useful to have a pdf available to download that represents the current release version.

Currently we could create version tag 0.1.0 and deliver the pdf. This way we avoid to make everyone to build the project, install the dependencies and "fight" against the troubles that can arise when building.

For example rebar3 project make the binary version available in each release, what is really cool.

Erik, I was waiting to buy your book before it was canceled. Thank you very much for make it available now as open source.

(see you at EUC2017 )   
Cheers

Pedro

**Comment by robertoaloi** [comment]
I would implement this as part of issue #10 . My idea is exactly to publish the PDF and the HTML pages (e.g. published as GitHub pages) as artifacts, as you say.
