### ISSUE TITLE
Bring in the beam instruction documentation automatically from the latest Erlang release

### ISSUE THREAD

**Issue by happi** [happi/theBeamBook#14]
The file genop.tab which is used to generate the appendix with beam instruction documentation should be pulled in as a dependency from Erlang/OTP.

Preferably without pulling in the whole Erlang repo.

**Comment by robertoaloi** [comment]
PR #24 removes the file from the repo and fetches it at build time (see Makefile).
For the time being, it fetches the latest version from the `master` branch, but if you prefer we can pin the version.
