### ISSUE TITLE
Strongly statically typed?

### ISSUE THREAD

**Issue by alexandrejbr** [happi/theBeamBook#18]
On type_system.asciidoc there's the following sentence:

> These aspects of the Erlang type system, strongly statically typed
with an order on the types puts some constraints on the implementation
of the language.

Given what is previously written in the chapter saying that Erlang is strongly statically typed confuses me. Is it really correct?

**Comment by happi** [comment]
No. It should say dynamically typed.
I have fixed it now.
Thanks.
