### ISSUE TITLE
HTML entities in code

### ISSUE THREAD

**Issue by dmitriid** [happi/theBeamBook#2]
Haven't looked through all code, but there are a few HTML entities here and there:

https://github.com/happi/theBeamBook/search?utf8=✓&q=%26gt%3B&type=

https://github.com/happi/theBeamBook/search?utf8=✓&q=%26lt%3B&type=

https://github.com/happi/theBeamBook/search?utf8=✓&q=%26amp%3B&type=

**Comment by happi** [comment]
Yes. They are needed when generating for a web backend.

Do they cause problems for you?

**Comment by dmitriid** [comment]
They end up in PDF versions as well :) Makes code look weird-ish :)

**Comment by essen** [comment]
They are not needed in Asciidoc, since it will properly escape when generating HTML.

**Comment by happi** [comment]
Yes. it is probably leftovers from one of the publishers build system. I'll remove them.

**Comment by happi** [comment]
Fixed.

**Comment by dmitriid** [comment]
woohoo!
