### ISSUE TITLE
Remove the Revision History from the book and add a THANKS section, instead

### ISSUE THREAD

**Issue by robertoaloi** [happi/theBeamBook#20]
The Revision History section in the book is becoming larger and larger and I see very little point in maintaining a complete history of the book inside the produced PDF, now that the project is open source. I would personally remove and add a THANKS section, instead (ideally automated by running the git log, extracting the contributors and u-sorting them. Opinions?

**Comment by happi** [comment]
Yes, I have been thinking the same thing. We should probably have a hand written contribution/author section for the main contributors and an autogenerated section for minor contributions.

**Comment by happi** [comment]
First step done.
The generated revision history is gone and a list of contributors is generated.

**Comment by robertoaloi** [comment]
As part of this ticket:

* happi should be excluded by the "other contributors" output
* Contributors should be sorted (desc) by number of contributions

**Comment by robertoaloi** [comment]
Done the two above steps (excluding happi and sorting).

**Comment by robertoaloi** [comment]
Also removed the empty list of collaborators and the revhistory sections generated by `dblatex` from the PDF.

**Comment by happi** [comment]
The list of contributors is missing in the latest 0.0.5 PDF build.

**Comment by robertoaloi** [comment]
@happi I already noticed and fixed it. Fix is in master.

**Comment by happi** [comment]
I will add an acknowledgement section at some point but we can do that as a separate issue.
The rev history is gone and contributors are listed.
I am closing this issue now.
