### ISSUE TITLE
BEAM file format: Add compact term encoding explanation

### ISSUE THREAD

**Issue by kvakvs** [happi/theBeamBook#36]
Compact term encoding is used by BEAM assembler to encode literal terms and special values (like register targets) inside the 'Code' section.

Here's my explanation with some code examples
http://beam-wisdoms.clau.se/en/latest/indepth-beam-file.html#beam-compact-term-encoding
I'll be happy to have parts of it taken/reworded/copy-pasted etc how you see fit.

**Comment by happi** [comment]
It would be great if you could work it into the chapter in beam_modules.asciidoc
you could also add a link to your original post if you like.

Alternatively, just let me know and I'll do it.

**Comment by kvakvs** [comment]
I am traveling now, will see what can be done, on or after this Friday.

**Comment by happi** [comment]
Great!
