### ISSUE TITLE
Missing source file msg.erl

### ISSUE THREAD

**Issue by hirotnk** [happi/theBeamBook#54]
In section 3.6.2, it refers to 

> embed file= "code/msg.erl"

But the file does not exist.

**Comment by michalwski** [comment]
Waiting for this file as well.

**Comment by robertoaloi** [comment]
@happi Do you have the file somewhere or should we produce it from scratch?

**Comment by happi** [comment]
Sorry, I fixed this in a branch a few days ago but forgot to merge.
Should be fixed now.
