### ISSUE TITLE
4.1 says Erlang type system is "strongly statically typed"

### ISSUE THREAD

**Issue by hirotnk** [happi/theBeamBook#56]
Is it a typo ?

**Comment by robertoaloi** [comment]
Hi @hirotnk, are you referring to this?

https://github.com/happi/theBeamBook/commit/61adf3954ffe79e8a83f5d13d5408af6de0d7ee0

If so, this has already been fixed. If not, please point out the file/line number.

**Comment by hirotnk** [comment]
@robertoaloi Ah I see, I missed the update, thank you !
