### ISSUE TITLE
Timer Wheel

### ISSUE THREAD

**Issue by hirotnk** [happi/theBeamBook#59]
There is a description below. In my understanding timer wheel exists per scheduler after around 18. Is it the case ?

> The timing wheel is a global resource and there might be contention for the write lock to the timing wheel if you have many processes inserting timers into the wheel

**Comment by garazdawi** [comment]
Yes, the timer wheel has been duplicated to hold one in each schedulers in Erlang/OTP 18.

**Comment by happi** [comment]
Thanks, 
the chapter was written before 18. I'll fix this.
