### ISSUE TITLE
Add a "Contributing" section to the README

### ISSUE THREAD

**Issue by robertoaloi** [happi/theBeamBook#64]
And ensure that things such as which Asciidoc dialect to use are included.

**Comment by happi** [comment]
Regarding the Asciidoc dialect I think the priorities should be:
1. The PDF target
2. The HTML target
3. Look OK directly on github

I do not know right now what that means for the style guide. We could start by adding these priorities to the style guide and then as we discover what works and what doesn't work we can add specific guidelines. 
If someone knows a set of Asciidoc  guidelines which we could start from please let me know.

Some other things that the guidelines should cover:

* How to mark/comment early drafts
* How to mark/comment missing sections where contributions are more than welcome
* What type of callout to use and for what (note, warning erc.)
* How to link to the OTP code
* Where to place files (code, screenshots, diagrams, etc) and how to handle them (Makefile, code listing appendix)
* How to tag chapters, sections, figures
