### ISSUE TITLE
Possible wording issue in scheduling section with regards to reduction checking

### ISSUE THREAD

**Issue by kylethebaker** [happi/theBeamBook#89]
In the _Scheduling: Non-preemptive, Reduction Counting_ section I think there is a minor mistake in the wording of the sixth paragraph, but I'm not 100% sure.

It reads:

> Each function call is counted as a reduction, and BEAM does a test upon entry to each function if the process has used up all its reductions.

Should this instead be (changes in bold):

> Each function call is counted as a reduction, and BEAM does a test upon entry to each function **[to check]** if the process has used up all its reductions.

It currently reads as if BEAM _only_ performs the test if the process has _already_ used up its reductions, but from surrounding context it seems like BEAM should be performing the test to determine if reductions are used up or not.

I'm not an expert (yet!) so this could just be my lack of understanding of how the BEAM works rather than an issue with the wording.

**Comment by happi** [comment]
You are right, the meaning is "to check". The BEAM test if the processes has used all reductions. I can see that it isn't clear. I will fix.

Thanks.
