### ISSUE TITLE
Docker image for building the book

### ISSUE THREAD

**Issue by robertoaloi** [happi/theBeamBook#9]
Provide a Docker image including all dependencies required to build the book, to avoid users and contributors having to install dependencies (well, apart from Docker).

**Comment by happi** [comment]
Sure.

**Comment by robertoaloi** [comment]
Working myself on this one.

**Comment by robertoaloi** [comment]
Image available at:

https://hub.docker.com/r/robertoaloi/docker-thebeambook/

Source:

https://github.com/robertoaloi/docker-thebeambook
