### ISSUE TITLE
BEAM instruction table bleeds into Code listsings in appendix 

### ISSUE THREAD

**Issue by gootik** [happi/theBeamBook#93]
<img width="1122" alt="screen shot 2017-08-14 at 13 46 14" src="https://user-images.githubusercontent.com/972202/29272235-186e3768-80f7-11e7-950f-35f1c5b68876.png">

**Comment by kvakvs** [comment]
I was the last person to modify the instruction table probably. I just double checked.
The bleeding does not happen when I build using Roberto Aloi's docker image. The resulting PDF is clean and the code listings are clean too.

**Comment by kvakvs** [comment]
Added few empty lines after the table hope this will fix it. Not sure how to test without merging
https://github.com/happi/theBeamBook/pull/94

**Comment by gootik** [comment]
Yeah I presume empty lines should fix the issue
