### ISSUE TITLE
Inspecting message handling example

### ISSUE THREAD

**Issue by gabrielrivas** [happi/theBeamBook#97]
I am stucked with the Inspecting message handling example:

4> P = spawn(fun() -> receive stop -> ok end end).
<0.63.0>
5> P ! start.
start
6> hipe_bifs:show_pcb(P).

It is supposed to show the message queue of a process like this:

...
  408 | msg.first     | 0x00007fd40962d880 |                    |
  416 | msg.last      | 0x00007fd40962d880 |                    |
  424 | msg.save      | 0x00007fd40962d880 |                    |
  432 | msg.len       | 0x0000000000000001 |                    |
  696 | msg_inq.first | 0x0000000000000000 |                    |
  704 | msg_inq.last  | 0x00007fd40a306238 |                    |
  712 | msg_inq.len   | 0x0000000000000000 |                    |
  616 | mbuf          | 0x0000000000000000 |                    |
  640 | mbuf_sz       | 0x0000000000000000 |                    |
...

All I see is :

P: 0x00007fd9ef6400b0
-----------------------------------------------
Offset| Name        | Value      | *Value     |
   72 | htop        | 0x00007fd9ec1bb020 |            |
   96 | hend        | 0x00007fd9ec1bb2d8 |            |
   88 | heap        | 0x00007fd9ec1bab90 |            |
  104 | heap_sz     | 0x00000000000000e9 |            |
   80 | stop        | 0x00007fd9ec1bb290 |            |
  592 | gen_gcs     | 0x0000000000000000 |            |
  594 | max_gen_gcs | 0x000000000000ffff |            |
  552 | high_water  | 0x00007fd9ec1bab90 |            |
  560 | old_hend    | 0x0000000000000000 |            |
  568 | old_htop    | 0x0000000000000000 |            |
  576 | old_head    | 0x0000000000000000 |            |
  112 | min_heap_.. | 0x00000000000000e9 |            |
  328 | rcount      | 0x0000000000000000 |            |
    0 | id          | 0x0000021000000423 |            |
  336 | reds        | 0x000000000000001a |            |
   16 | tracer      | 0xfffffffffffffffb |            |
   24 | trace_fla.. | 0x0000000000000000 |            |
  344 | group_lea.. | 0x0000019800000333 |            |
  352 | flags       | 0x0000000000002004 |            |
  360 | fvalue      | 0x000000000000640b |            |
  368 | freason     | 0x000000000000000a |            |
  320 | fcalls      | 0x00000000000007c9 |            |
  384 | next        | 0x00007fd9ef6444b0 |            |
   48 | reg         | 0x0000000000000000 |            |
   56 | nlinks      | 0x0000000000000000 |            |
  616 | mbuf        | 0x0000000000000000 |            |
  640 | mbuf_sz     | 0x0000000000000000 |            |
  464 | dictionary  | 0x0000000000000000 |            |
  472 | seq..clock  | 0x0000000000000000 |            |
  480 | seq..astcnt | 0x0000000000000000 |            |
  488 | seq..token  | 0xfffffffffffffffb |            |
  496 | intial[0]   | 0x000000000000320b |            |
  504 | intial[1]   | 0x0000000000000c8b |            |
  512 | intial[2]   | 0x0000000000000002 |            |
  520 | current     | 0x0000000000000000 | 0xffffffffffffffff |
  296 | cp          | 0x0000000000000000 | 0xffffffffffffffff |
  304 | i           | 0x00007fd9ed8294c8 | 0x000000000043f0bb |
  312 | catches     | 0x0000000000000000 |            |
  224 | arity       | 0x0000000000000000 |            |
  232 | arg_reg     | 0x00007fd9ef6401a8 | 0x000000000000320b |
  240 | max_arg_reg | 0x0000000000000006 |            |
  248 | def..reg[0] | 0x000000000000320b |            |
  256 | def..reg[1] | 0x0000000000000c8b |            |
  264 | def..reg[2] | 0x00007fd9ec1bab91 |            |
  272 | def..reg[3] | 0x0000000000000000 |            |
  280 | def..reg[4] | 0x0000000000000000 |            |
  288 | def..reg[5] | 0x00000000000007d0 |            |
  136 | nsp         | 0x0000000000000000 |            |
  144 | nstack      | 0x0000000000000000 |            |
  152 | nstend      | 0x0000000000000000 |            |
  160 | ncallee     | 0x0000000000000000 |            |
   56 | ncsp        | 0x0000000000000000 |                    |
   64 | narity      | 0x0000000000000000 |                    |
-----------------------------------------------
true

What am I missing?

**Comment by happi** [comment]
Sorry, this is sort of the expected behaviour, I was hoping that I would have submitted and gotten the patch for hipe_bifs accepted upstreams in the latest OTP version, alas that has not happened yet.

As it says in the processess chapter:
  "Many of the HiPE BIFs where written by the author in the mid nineties (before 64 bits Erlang existed) and the printouts on a 64 bit machine might be a bit off. There are new versions of these BIFs that do a better job, hopefully they will be included in ERTS at the time of the printing of this book. Otherwise you can build your own version with the patch provided in the code section and the instructions in [CH-BuildingERTS]."

Unfortunately I had not included the patch in the source code listing.

I have added the patch in the branch hipe_patch.

Hope to merge it to master soon. I will also submit it to OTP.

**Comment by gabrielrivas** [comment]
Thanks for your response. I understand now why I could not get info about it on the web. Is there any other way in which the message passing could be inspected with the actual Erlang/OTP implementation?

**Comment by happi** [comment]
That depends on what type of inspection you need.

What are you trying to achieve?
tis 19 sep. 2017 kl. 15:29 skrev gabrielrivas <notifications@github.com>:

**Comment by gabrielrivas** [comment]
Right now, I am mostly interested on learning the interaction mechanisms between modules and BIFs. In the long term I am interested in having something like the book mentions "BEAM on a FPGA", all I could find about it is an old PPT presentation about the ECOMP project, but no opensource code or anything.  I will try building that patch you mention in my own OTS build, and tinker with the code, Thanks.
